site_name: MilleNuits

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Accueil: index.md

  - Mission 1 - Documentation:
      - Installation MkDocs: mission1.md

  - Mission 2 - Documentation:
      - Installation Poste client: mission2.md

  - Mission 3 - Documentation:
      - Mise en place FOG: mission3.md
      - Comparatif & Solutions: comparatif.md

  - Mission 4 - Documentation:
      - Mise en place de GLPI: mission GLPI.md
