site_name: MilleNuits

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
nav:
  - Accueil: index.md

  - SP2:
      - Installation MkDocs: mission1.md
      - Installation Poste client: mission2.md
      - Outil de déploiement de poste : mission3.md
      - Comparatif et Solutions : comparatif.md
      - Outil de gestion d'incidents : mission GLPI.md

  - SP3:
      - Mise en place de Windows Server 2019: mission6.md
      - Mise en place du Serveur DHCP: mission5.md
      - Mise en place d'un NAS avec Authentificatiion Active Directory : mission7.md
      
  - SP4:
      - DMZ et DOcker: misson8.md
