site_name: MilleNuits

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Accueil : docs/index.md

  - Mission 1 - Documentation : 
  - Installation MkDocs : docs/SP2-Mission-1-Création d'une Documentation avec Mkdocs et github pages.md

  - Mission 2 - Documentation : 
  - Installation Poste client : docs/SP2-Mission2-Installation de nouveaux postes clients.md

  - Mission 3 - Documentation : 
  - Mise en place FOG : docs/SP2 - Mission 3 -  Recherche et mise en place d’un outil de déploiement des postes.md
